---
apiVersion: batch/v1
kind: Job
metadata:
  generateName: generate-requests-
spec:
  template:
    spec:
      containers:
      - image: quay.io/zroubalik/hey
        name: hey
        env:
          - name: ROUTE
            value: http://keda-hpa-test:8888
        # generate moderate load of (2*10) per second for roughly 3000/(2*10) seconds
        args:
          - -c
          - "2"
          - -q
          - "10"
          - -n
          - "3000"
          - "$(ROUTE)"
      restartPolicy: Never
  activeDeadlineSeconds: 120
  backoffLimit: 2