kind: Deployment
apiVersion: apps/v1
metadata:
  name: keda-hpa-test-d
  namespace: keda-test
  labels:
    app.kubernetes.io/instance: keda-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keda-hpa-test
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: keda-hpa-test
    spec:
      restartPolicy: Always
      serviceAccountName: default
      imagePullSecrets:
        - name: nexus-image-pull
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      containers:
        - name: keda-hpa-test
          image: 'docker.io/nitesh8011/maven:hpa_keda'
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      serviceAccount: default
      dnsPolicy: ClusterFirst
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: keda-hpa-test
  namespace: keda-test
  labels:
    app: keda-hpa-test
spec:
  ports:
    - name: web
      protocol: TCP
      port: 8888
      targetPort: 8888
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: keda-hpa-test