apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: keda-trigger-auth-prometheus
spec:
  secretTargetRef:
    - key: token
      name: thanos-token
      parameter: bearerToken
    - key: ca.crt
      name: thanos-token
      parameter: ca