---
# https://github.com/rhobs/prometheus-example-app

namespace: openshift-keda

generatorOptions:
  disableNameSuffixHash: true

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  # - route.yaml
