apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: prometheus-metrics-monitor
  name: prometheus-sm
  namespace: keda-test
spec:
  endpoints:
    - interval: 30s
      port: web
      scheme: http
  namespaceSelector:
    matchNames:
      - keda-test
  selector:
    matchLabels:
      app: prometheus-metrics-app