---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: static-app
    app.kubernetes.io/component: static-app
    app.kubernetes.io/instance: static-app
  name: static-app
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: ""
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
  labels:
    app: static-app
    app.kubernetes.io/component: static-app
    app.kubernetes.io/instance: static-app
  name: static-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: static-app:latest
  postCommit: {}
  resources: {}
  source:
    contextDir: htdocs
    git:
      ref: dev
      uri: https://github.com/dlbewley/static.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nginx:1.20-ubi8
        namespace: openshift
    type: Source
  triggers:
  - github:
      secret: 07E2a5yTofDIND7glPn2
    type: GitHub
  - generic:
      secret: d3IwjN_UvSk9cU2QP2QI
    type: Generic
  - type: ConfigChange
  - imageChange: {}
    type: ImageChange
status:
  lastVersion: 0
---
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"static-app:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"static-app\")].image"}]'
  name: static-app-d
  namespace: keda-test
  labels:
    app: static-app
    app.kubernetes.io/component: static-app
    app.kubernetes.io/instance: static-app
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: static-app
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: static-app
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: static-app
          image: 'image-registry.openshift-image-registry.svc:5000/keda-test/static-app@sha256:6184d7885347a8fb6108ecea29d3920b9462e755994310c3168e2097bfcbe58d'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
---
kind: Service
apiVersion: v1
metadata:
  name: static-app
  namespace: keda-test
  labels:
    app: static-app
    app.kubernetes.io/component: static-app
    app.kubernetes.io/instance: static-app
spec:
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: static-app
---
# apiVersion: route.openshift.io/v1
# kind: Route
# metadata:
#   labels:
#     app: static-app
#     app.kubernetes.io/component: static-app
#     app.kubernetes.io/instance: static-app
#   name: static-app
# spec:
#   port:
#     targetPort: 8080-tcp
#   to:
#     kind: ""
#     name: static-app
#     weight: null
# status: {}